In [1]:
import numpy as np
from random import randint
a = int(input("Введите число 1:"))
b = int(input("Введите число 2:"))
m = np.array([[randint(0,100) for i in range (a)] for j in range (b)])
print(m)

Введите число 1:5
Введите число 2:6
[[100   0  99  91  43]
 [  1  54  61   7  25]
 [ 28  20  67  21   7]
 [ 98  60  70  80  59]
 [ 21  79  14  26  39]
 [ 23   7  84  92  33]]


In [7]:
import numpy as np
import random
a = int(input("Введите число больше 2:"))
variants = [-1,1]
m = np.array([[random.choice(variants) for i in range (a)] for j in range (a)])
sum = 0
for i in range(a):
    for j in range(a):
        sum += m[i][j]
print (m)        
print (sum)

Введите число больше 2:5
[[-1 -1 -1 -1  1]
 [-1  1  1 -1  1]
 [-1 -1  1 -1  1]
 [-1  1 -1  1 -1]
 [-1 -1  1  1 -1]]
-5
